---
name: "build frontend"
on:
  push:
    paths:
      - 'rss_frontend/**'
      - 'flake.nix'
      - 'flake.lock'
  pull_request:
    paths:
      - 'rss_frontend/**'
      - 'flake.nix'
      - 'flake.lock'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            sandbox = false
      - name: Build package
        run: nix build .#rss-frontend --option sandbox false
