---
name: "Lint and test PR's for poller"
on:
  push:
    pull_request:
    paths: 
     - 'rss_poller/*'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        system:
          - x86_64-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          enable_kvm: true
          extra_nix_config: |
            sandbox = false
      - run: |
            cd rss_poller && nix flake check --option sandbox false
